config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root 'pages#index'
    get :about, :contacts, :faq, :sitemap, controller: :pages
    resources :posts, only: %i[index show]
    resources :courses, path: :talks, only: %i[index show]
    get 'courses/:id', to: redirect('/talks/%{id}')
    get 'courses', to: redirect('/talks')
    resources :speakers, :showcases, only: :index
    post 'rental/calculate'
  end

  get Settings.admin_path_prefix, to: "admin#dashboard", as: :admin_root
  # back
  namespace :admin, path: Settings.admin_path_prefix do
    get :space_price
    resources :posts do
      put :sort, on: :collection
      get :preview, on: :member
    end
    resources :courses, :authors, :speakers, :faqs, :categories, :showcases, :videos, :interview_questions do
      put :sort, on: :collection
    end
    resources :translations, only: %i[index create update]
  end

  # plugins
  resources :redactor_images, :contacts, only: :create
end

app/models/admin/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Admin::Author < Author
  # scope macros

  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  has_many :posts

  # validation macros

  # callbacks

  # other

  protected
  # callback methods
end

app/models/author.rb
class Author < ActiveRecord::Base
  # scope macros

  # Concerns macros

  # Constants

  # Attributes related macros

  # association macros
  has_many :posts

  # validation macros

  # callbacks

  # other
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController
  before_action :set_admin_author, only: [:show, :edit, :update, :destroy]

  # GET /admin/authors
  # GET /admin/authors.json
  def index
    @admin_authors = Admin::Author.all.order('id DESC').page(params[:page])
  end

  # GET /admin/authors/1
  # GET /admin/authors/1.json
  def show
  end

  # GET /admin/authors/new
  def new
    @admin_author = Admin::Author.new
  end

  # GET /admin/authors/1/edit
  def edit
  end

  # POST /admin/authors
  # POST /admin/authors.json
  def create
    @admin_author = Admin::Author.new(admin_author_params)

    respond_to do |format|
      if @admin_author.save
        format.html { redirect_to @admin_author, notice: t('crud.created_successfully!', name: Admin::Author.model_name.human) }
        format.json { render :show, status: :created, location: @admin_author }
      else
        format.html { render :new }
        format.json { render json: @admin_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/authors/1
  # PATCH/PUT /admin/authors/1.json
  def update
    respond_to do |format|
      if @admin_author.update(admin_author_params)
        format.html { redirect_to @admin_author, notice: t('crud.updated_successfully!', name: Admin::Author.model_name.human) }
        format.json { render :show, status: :ok, location: @admin_author }
      else
        format.html { render :edit }
        format.json { render json: @admin_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/authors/1
  # DELETE /admin/authors/1.json
  def destroy
    @admin_author.destroy
    respond_to do |format|
      format.html { redirect_to admin_authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_author
      @admin_author = Admin::Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_author_params
      params.require(:admin_author).permit(:name)
    end
end

app/views/admin/authors/_form.html.erb
<%= simple_form_for(@admin_author) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<h1><%= t('crud.edit!', resource: Admin::Author.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<div class="btn-group">
  <%= link_to t('crud.show'), @admin_author, class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_authors_path, class: 'btn btn-default btn-lg' %>
</div>

app/views/admin/authors/index.html.erb
<h1><%= Admin::Author.model_name.human %> <%= link_to t('crud.new'), new_admin_author_path, class: 'btn btn-lg btn-success' %></h1>

<%= paginate @admin_authors %>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <%= th_for Admin::Author, :id, :name %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_authors.each do |admin_author| %>
      <tr>
        <%= td_for admin_author, :id, :name %>
        <%= td_action_for admin_author %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @admin_authors %>

app/views/admin/authors/new.html.erb
<h1><%= t('crud.new!', resource: Admin::Author.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<%= link_to t('action.back'), admin_authors_path, class: 'btn btn-default btn-lg' %>

app/views/admin/authors/show.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <th>屬性</th>
    <th>值</th>
  </thead>
  <tbody>
    <%= tr_for @admin_author, :id, :name %>
  </tbody>
</table>
<div class="btn-group">
  <%= link_to t('crud.edit'), edit_admin_author_path(@admin_author), class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_authors_path, class: 'btn btn-default btn-lg' %>
</div>