config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root 'pages#index'
    get :about, :contacts, :faq, :sitemap, controller: :pages
    resources :posts, only: %i[index show]
    resources :courses, path: :talks, only: %i[index show]
    get 'courses/:id', to: redirect('/talks/%{id}')
    get 'courses', to: redirect('/talks')
    resources :speakers, :showcases, only: :index
    post 'rental/calculate'
  end

  get Settings.admin_path_prefix, to: "admin#dashboard", as: :admin_root
  # back
  namespace :admin, path: Settings.admin_path_prefix do
    get :space_price
    resources :posts do
      put :sort, on: :collection
      get :preview, on: :member
    end
    resources :courses, :authors, :speakers, :faqs, :categories, :showcases, :videos, :interview_questions do
      put :sort, on: :collection
    end
    resources :translations, only: %i[index create update]
  end

  # plugins
  resources :redactor_images, :contacts, only: :create
end

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">後台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav">
        <li><%= link_to('回到前台', root_path) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <%= content_tag :li, link_to('總覽', admin_root_path), class: (:active if request.path == admin_root_path) %>
  <% [Admin::Post, Admin::Author, Admin::Category, Admin::Course, Admin::Speaker, Admin::Faq, Admin::Showcase, Admin::Video, Admin::InterviewQuestion].each do |model| %>
    <%= nav_li_for model %>
  <% end %>
  <%= nav_li Translation.model_name.human, [:admin, Translation, model: :Faq, lc: :en], match: '/translations', method: :[] %>
  <%= nav_li '空間租用試算表', admin_space_price_path %>
</ul>