config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root 'pages#index'
    get :about, :contacts, :faq, :sitemap, controller: :pages
    resources :posts, only: %i[index show]
    resources :courses, path: :talks, only: %i[index show]
    get 'courses/:id', to: redirect('/talks/%{id}')
    get 'courses', to: redirect('/talks')
    resources :speakers, :showcases, only: :index
    post 'rental/calculate'
  end

  get Settings.admin_path_prefix, to: "admin#dashboard", as: :admin_root
  # back
  namespace :admin, path: Settings.admin_path_prefix do
    get :space_price
    resources :posts do
      put :sort, on: :collection
      get :preview, on: :member
    end
    resources :courses, :authors, :speakers, :faqs, :categories, :showcases, :videos, :interview_questions do
      put :sort, on: :collection
    end
    resources :translations, only: %i[index create update]
  end

  # plugins
  resources :redactor_images, :contacts, only: :create
end

app/models/admin/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :integer          not null, primary key
#  name           :string(255)      not null
#  created_at     :datetime
#  updated_at     :datetime
#  courses_count  :integer          default(0), not null
#  is_highlighted :boolean          default(FALSE), not null
#  sort_id        :integer          default(0), not null
#  permalink      :string(255)      not null
#

class Admin::Category < Category
  # scope macros

  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  has_many :courses

  # validation macros

  # callbacks

  # other

  protected
  # callback methods
end

app/models/category.rb
class Category < ActiveRecord::Base
  # scope macros
  scope :with_max_date, -> { select('categories.*, max(date) as max_date').joins(courses: :stages).group('categories.id') }

  # Concerns macros
  include Permalinkable

  # Constants

  # Attributes related macros
  permalinkable

  # association macros
  has_many :courses, -> { where(is_online: true) }

  # validation macros
  validates :name, presence: true

  # callbacks

  # other
  def new_course?
    if respond_to?(:max_date)
      max_date > Time.now
    else
      logger.warn 'Use `Category.with_max_date` for better performance.'
      courses.select('courses.*, max(date) as max_date').joins(:stages).group('courses.id').order('max_date desc').first.max_date > Time.now
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  include Sortable
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Admin::Category.order(:sort_id).page(params[:page])
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Admin::Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Admin::Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to @admin_category, notice: t('crud.created_successfully!', name: Admin::Category.model_name.human) }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to @admin_category, notice: t('crud.updated_successfully!', name: Admin::Category.model_name.human) }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Admin::Category.find_by!(permalink: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.require(:admin_category).permit(:name, :is_highlighted, :permalink)
    end
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for(@admin_category) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :permalink %>
    <%= f.input :is_highlighted, hint:"若勾選則該講座分類會出現在前台頁面 Footer" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t('crud.edit!', resource: Admin::Category.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<div class="btn-group">
  <%= link_to t('crud.show'), @admin_category, class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_categories_path, class: 'btn btn-default btn-lg' %>
</div>

app/views/admin/categories/index.html.erb
<%= form_tag sort_admin_categories_path, method: :put do |f| %>
<h1><%= Admin::Category.model_name.human %> <%= link_to t('crud.new'), new_admin_category_path, class: 'btn btn-lg btn-success' %> <%= submit_tag '更新排序', class: 'btn btn-lg btn-primary' %></h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th></th>
      <%= th_for Admin::Category, :id, :name, :permalink, :is_highlighted %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody class="sortable" data-items=".admin_category">
    <% @admin_categories.each do |admin_category| %>
      <%= content_tag_for :tr, admin_category do %>
        <%= hidden_field_tag "sort[#{admin_category.id}][sort_id]", admin_category.sort_id %>
        <td><i class="glyphicon glyphicon-move"></i></td>
        <%= td_for admin_category, :id, :name, :permalink, :is_highlighted %>
        <%= td_action_for admin_category %>
      <% end %>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/admin/categories/new.html.erb
<h1><%= t('crud.new!', resource: Admin::Category.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<%= link_to t('action.back'), admin_categories_path, class: 'btn btn-default btn-lg' %>

app/views/admin/categories/show.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <th>屬性</th>
    <th>值</th>
  </thead>
  <tbody>
    <%= tr_for @admin_category, :id, :name, :permalink, :is_highlighted %>
  </tbody>
</table>
<div class="btn-group">
  <%= link_to t('crud.edit'), edit_admin_category_path(@admin_category), class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_categories_path, class: 'btn btn-default btn-lg' %>
</div>