config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root 'pages#index'
    get :about, :contacts, :faq, :sitemap, controller: :pages
    resources :posts, only: %i[index show]
    resources :courses, path: :talks, only: %i[index show]
    get 'courses/:id', to: redirect('/talks/%{id}')
    get 'courses', to: redirect('/talks')
    resources :speakers, :showcases, only: :index
    post 'rental/calculate'
  end

  get Settings.admin_path_prefix, to: "admin#dashboard", as: :admin_root
  # back
  namespace :admin, path: Settings.admin_path_prefix do
    get :space_price
    resources :posts do
      put :sort, on: :collection
      get :preview, on: :member
    end
    resources :courses, :authors, :speakers, :faqs, :categories, :showcases, :videos, :interview_questions do
      put :sort, on: :collection
    end
    resources :translations, only: %i[index create update]
  end

  # plugins
  resources :redactor_images, :contacts, only: :create
end

app/models/admin/video.rb
# == Schema Information
#
# Table name: videos
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  iframe      :string(255)
#  summary     :string(255)
#  description :text
#  is_online   :boolean
#  created_at  :datetime
#  updated_at  :datetime
#  image       :string(255)
#

class Admin::Video < Video
  # scope macros

  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  has_and_belongs_to_many :speakers

  # validation macros

  # callbacks

  # other

  protected
  # callback methods
end

app/models/video.rb
class Video < ActiveRecord::Base
  # scope macros

  # Concerns macros

  # Constants

  # Attributes related macros
  mount_uploader :image, VideoImageUploader

  # association macros
  has_and_belongs_to_many :speakers
  has_many :translations, as: :translatable

  # validation macros

  # callbacks

  # other
  def next
    self.class.where('id > ?', id).first
  end

  def previous
    self.class.where('id < ?', id).last
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  before_action :set_admin_video, only: [:show, :edit, :update, :destroy]

  # GET /admin/videos
  # GET /admin/videos.json
  def index
    @admin_videos = Admin::Video.all.order('id DESC').page(params[:page])
  end

  # GET /admin/videos/1
  # GET /admin/videos/1.json
  def show
  end

  # GET /admin/videos/new
  def new
    @admin_video = Admin::Video.new
  end

  # GET /admin/videos/1/edit
  def edit
  end

  # POST /admin/videos
  # POST /admin/videos.json
  def create
    @admin_video = Admin::Video.new(admin_video_params)

    respond_to do |format|
      if @admin_video.save
        format.html { redirect_to @admin_video, notice: t('crud.created_successfully!', name: Admin::Video.model_name.human) }
        format.json { render :show, status: :created, location: @admin_video }
      else
        format.html { render :new }
        format.json { render json: @admin_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/videos/1
  # PATCH/PUT /admin/videos/1.json
  def update
    respond_to do |format|
      if @admin_video.update(admin_video_params)
        format.html { redirect_to (params[:ref] || @admin_video), notice: t('crud.updated_successfully!', name: Admin::Video.model_name.human) }
        format.json { render :show, status: :ok, location: @admin_video }
      else
        format.html { render :edit }
        format.json { render json: @admin_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/videos/1
  # DELETE /admin/videos/1.json
  def destroy
    @admin_video.destroy
    respond_to do |format|
      format.html { redirect_to admin_videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_video
      @admin_video = Admin::Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_video_params
      params.require(:admin_video).permit(:title, :iframe, :summary, :description, :is_online, :image, :remove_image, :image_cache, speaker_ids: [])
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.includes(:translations).where(is_online: true).order(id: :desc).page(params[:page]).per(9)
  end

  def show
    @video = Video.find(params[:id])
    @next = @video.next
    @previous = @video.previous
    @seo = {
      meta: {
        description: @video.summary
      },
      google: {
        name: @video.title,
        description: @video.summary,
        item_type: :VideoObject
      },
      og: {
        title: @video.title,
        url: video_url(@video),
        type: :'video.episode',
        description: @video.summary
      }
    }
  end
end

app/views/admin/videos/_form.html.erb
<%= simple_form_for(@admin_video) do |f| %>

  <div class="form-inputs">
    <%= f.association :speakers, input_html: {class: 'select2'} %>
    <%= f.input :title %>
    <%= f.input :image, hint: '最佳大小 360x220' %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.input :remove_image, as: :boolean %>
    <%= f.input :iframe %>
    <%= f.input :summary, as: :text, hint: '最多 150 字，剩 <span id="summary_remain"></span> 個字，用在 meta tag 和 videos/index 頁面'.html_safe %>
    <%= f.input :description, input_html: {class: :redactor} %>
    <%= f.input :is_online %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/admin/videos/edit.html.erb
<h1><%= t('crud.edit!', resource: Admin::Video.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<div class="btn-group">
  <%= link_to t('crud.show'), @admin_video, class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_videos_path, class: 'btn btn-default btn-lg' %>
</div>

app/views/admin/videos/index.html.erb
<h1><%= Admin::Video.model_name.human %> <%= link_to t('crud.new'), new_admin_video_path, class: 'btn btn-lg btn-success' %></h1>

<%= paginate @admin_videos %>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <%= th_for Admin::Video, :id, :is_online, :image, :title, :summary %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_videos.each do |admin_video| %>
      <tr>
        <%= td_for admin_video, :id, td_is_online(admin_video), :image, :title, :summary %>
        <%= td_action_for admin_video %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @admin_videos %>

app/views/admin/videos/new.html.erb
<h1><%= t('crud.new!', resource: Admin::Video.model_name.human) %></h1>

<%= render 'form' %>
<hr>
<%= link_to t('action.back'), admin_videos_path, class: 'btn btn-default btn-lg' %>

app/views/admin/videos/show.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <th>屬性</th>
    <th>值</th>
  </thead>
  <tbody>
    <%= tr_for @admin_video, :id, :title, tr_speakers(@admin_video), :image, :iframe, :summary, :description, :is_online %>
  </tbody>
</table>
<div class="btn-group">
  <%= link_to t('crud.edit'), edit_admin_video_path(@admin_video), class: 'btn btn-info btn-lg' %>
  <%= link_to t('action.back'), admin_videos_path, class: 'btn btn-default btn-lg' %>
</div>